services:
  mysql:
    image: mysql:8.0
    container_name: food-roulette-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Frigide9!
      MYSQL_DATABASE: food_roulette
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: OMD1EleC!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
